# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Math Spinners
email: kylejking@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  <p>Spinners are a fun way to practice multiplication and division. </p>
  <p>Choose a base and spin!
  The arrow on one side points to a number to multiple or divide with the base and the arrow on the flip side points to the answer.
  </p>
  <p>To order a set, reach out to <a href='mail&#116;o&#58;kyl&#101;jk&#105;ng&#64;gm%61il&#46;&#99;%6F&#109;'>kyle&#106;king&#64;gmail&#46;c&#111;m</a>
  </p>

baseurl: "/spinners" # the subpath of your site, e.g. /blog
url: "https://kylekyle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: kyl
# github_username:  kylekyle
show_downloads: false

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
